"use client";
import React, { createContext, useContext, useState, ReactNode } from "react";

type Lang = "fr" | "es";

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  fr: {
    // Navbar
    "nav.about": "À propos",
    "nav.resume": "CV",
    "nav.projects": "Projets",
    "nav.contact": "Contact",
    "nav.blog": "Blog",
    "nav.services": "Services",
    // Header
    "header.badge": "Développeur Full-stack · Founder & CEO · IA & Automatisation",
    "header.greeting": "Je suis",
    "header.name": "Andrew Alfaro",
    "header.description": "Développeur Full-stack passionné par la création d'applications web performantes et l'automatisation des processus d'entreprise par l'IA. Founder & CEO de Jumper Enterprise, spécialisé en React, Next.js, TypeScript et Deno. Plus de 4 ans d'expérience en France.",
    "header.cta.resume": "Voir mon CV",
    "header.cta.projects": "Mes Projets",
    "header.stat.years": "Ans d'expérience",
    "header.stat.projects": "Projets livrés",
    "header.stat.companies": "Entreprises",
    // Hero
    "hero.title1": "Je crée des",
    "hero.title2": "expériences web exceptionnelles",
    "hero.subtitle": "Développeur Full-stack · Fondateur Jumper Enterprise · Automatisation IA · React · Next.js · TypeScript",
    "hero.cta": "Voir mes projets",
    // About
    "about.title": "À propos de moi",
    "about.intro": "Développeur Full-stack avec plus de 4 ans d'expérience, fondateur de Jumper Enterprise — une startup spécialisée dans l'automatisation des ventes et du marketing par l'IA. Je conçois des applications web performantes et j'automatise les processus métier pour maximiser la productivité des entreprises.",
    "about.p1": "Mon expertise couvre le développement front-end avec React, Next.js et TypeScript, le développement back-end avec Node.js, Deno et PostgreSQL, ainsi que l'intégration d'agents IA et d'automatisations via n8n et Make.",
    "about.p2": "En tant que Founder & CEO de Jumper Enterprise, je pilote le développement de solutions d'agents IA pour la gestion des ventes, du marketing et du support client, permettant aux entreprises de fonctionner 24/7 de manière automatisée.",
    "about.p3": "Je contribue également à des projets open source, notamment Yumi Lab, et je reste à la pointe des nouvelles technologies pour apporter toujours plus de valeur à mes clients.",
    "about.education": "Éducation & Certifications",
    "about.social": "Retrouvez-moi sur",
    // Resume
    "resume.title": "CV Interactif",
    "resume.subtitle": "Full-stack Developer · Founder & CEO · AI Solutions",
    "resume.summary": "Développeur Full-stack passionné avec plus de 4 ans d'expérience, spécialisé en JavaScript, React, TypeScript et Node.js. Fondateur de Jumper Enterprise, expert en automatisation des processus business par l'IA. Reconnu pour mon autonomie, ma capacité d'innovation et ma maîtrise des architectures modernes.",
    "resume.experience": "Expérience Professionnelle",
    "resume.education": "Formation",
    "resume.skills": "Compétences Techniques",
    "resume.languages": "Langues",
    "resume.softskills": "Soft Skills",
    "resume.contact": "Contact",
    "resume.present": "Présent",
    // Services
    "services.title": "Mes Services",
    "services.subtitle": "Solutions web sur mesure, automatisation IA et consulting technologique pour booster votre business.",
    "services.cta": "Voir tous mes services",
    "services.web.title": "Développement Web Full-stack",
    "services.web.desc": "Applications React/Next.js performantes, APIs REST, bases de données et déploiement cloud.",
    "services.ai.title": "Agents IA & Automatisation",
    "services.ai.desc": "Agents intelligents pour ventes, marketing, support client et gestion des opérations via n8n et Make.",
    "services.shopify.title": "E-Commerce & Shopify",
    "services.shopify.desc": "Boutiques Shopify personnalisées, intégration de paiements Stripe/SEPA et optimisation des conversions.",
    // Services page
    "servicespage.hero.tag": "Disponible · Freelance & CDI",
    "servicespage.hero.title": "Transformez vos idées en réalité",
    "servicespage.hero.subtitle": "Expert Full-stack & Founder de Jumper Enterprise. Je conçois des applications web performantes et automatise vos processus métier grâce à l'IA pour booster votre croissance.",
    "servicespage.hero.cta.main": "Découvrir Jumper Enterprise",
    "servicespage.hero.cta.contact": "Discutons de votre projet",
    "servicespage.offer.title": "Ce que je propose",
    "servicespage.offer.subtitle": "Solutions sur mesure pour startups, PME et grands comptes.",
    "servicespage.s1.title": "Développement Web Full-stack",
    "servicespage.s1.desc": "Applications React/Next.js performantes, SEO optimisé, APIs REST robustes et intégrations tierces.",
    "servicespage.s1.f1": "React, Next.js, TypeScript",
    "servicespage.s1.f2": "APIs REST & bases de données",
    "servicespage.s1.f3": "SSR / SSG / ISR",
    "servicespage.s1.f4": "Tests & déploiement CI/CD",
    "servicespage.s2.title": "Agents IA & Automatisation",
    "servicespage.s2.desc": "Agents intelligents pour automatiser ventes, marketing, support client et opérations via n8n, Make et Python.",
    "servicespage.s2.f1": "Agents IA sur mesure",
    "servicespage.s2.f2": "Workflows n8n & Make",
    "servicespage.s2.f3": "Intégration OpenAI / LLM",
    "servicespage.s2.f4": "Automatisation 24/7",
    "servicespage.s3.title": "E-Commerce & Shopify",
    "servicespage.s3.desc": "Boutiques Shopify personnalisées, optimisation des conversions, intégration Stripe/SEPA et dashboards de vente.",
    "servicespage.s3.f1": "Themes Shopify sur mesure",
    "servicespage.s3.f2": "Stripe, SEPA, PayPal",
    "servicespage.s3.f3": "Dashboard KPI & analytics",
    "servicespage.s3.f4": "Mobile-first & SEO",
    "servicespage.s4.title": "Consulting Technologique",
    "servicespage.s4.desc": "Audit de votre stack, recommandations d'architecture, accompagnement équipe et formation aux bonnes pratiques.",
    "servicespage.s4.f1": "Audit & code review",
    "servicespage.s4.f2": "Architecture scalable",
    "servicespage.s4.f3": "Formation & mentoring",
    "servicespage.s4.f4": "Clean Code & CI/CD",
    "servicespage.process.title": "Mon processus de travail",
    "servicespage.process.s1": "Découverte",
    "servicespage.process.s1.desc": "Analyse de vos besoins et définition du périmètre",
    "servicespage.process.s2": "Conception",
    "servicespage.process.s2.desc": "Architecture, maquettes et plan technique détaillé",
    "servicespage.process.s3": "Développement",
    "servicespage.process.s3.desc": "Sprints agiles avec livraisons régulières",
    "servicespage.process.s4": "Livraison",
    "servicespage.process.s4.desc": "Tests, déploiement et support post-lancement",
    "servicespage.reviews.title": "Ce que disent les clients",
    "servicespage.reviews.loading": "Chargement des avis...",
    "servicespage.reviews.empty": "Soyez le premier à laisser un avis !",
    "servicespage.review.form.title": "Laisser un avis",
    "servicespage.review.form.name": "Votre nom",
    "servicespage.review.form.name.ph": "Nom ou pseudonyme...",
    "servicespage.review.form.comment": "Votre avis",
    "servicespage.review.form.comment.ph": "Partagez votre expérience...",
    "servicespage.review.form.submit": "Envoyer l'avis",
    "servicespage.review.form.rating": "Note",
    // Contact
    "contact.title": "Contactez-moi",
    "contact.subtitle": "Disponible pour des missions freelance, des opportunités CDI ou des collaborations. Répondre sous 24h.",
    "contact.name": "Nom complet",
    "contact.name.ph": "Votre nom...",
    "contact.email": "Email",
    "contact.email.ph": "votre@email.com",
    "contact.phone": "Téléphone",
    "contact.phone.ph": "+33 6 XX XX XX XX",
    "contact.subject": "Sujet",
    "contact.subject.ph": "Projet web, freelance, CDI...",
    "contact.message": "Message",
    "contact.message.ph": "Décrivez votre projet ou opportunité...",
    "contact.send": "Envoyer le message",
    "contact.sending": "Envoi en cours...",
    "contact.success": "Message envoyé ! Je vous réponds sous 24h.",
    "contact.error": "Erreur lors de l'envoi. Veuillez réessayer.",
    "contact.info.title": "Restons en contact",
    "contact.info.available": "Disponible maintenant",
    "contact.info.location": "Île-de-France, France",
    "contact.info.response": "Réponse sous 24h",
    "contact.info.freelance": "Freelance & CDI",
    // Projects
    "projects.title": "Mes Projets",
    "projects.subtitle": "Applications web full-stack, automatisation IA, e-commerce et outils développeur.",
    "projects.filter.all": "Tous",
    "projects.filter.web": "Web App",
    "projects.filter.ai": "IA & Auto",
    "projects.filter.ecommerce": "E-Commerce",
    "projects.filter.tools": "Outils",
    "projects.cta.details": "Voir les détails",
    "projects.cta.demo": "Demo",
    "projects.cta.code": "Code",
    "projects.featured": "Projet vedette",
    // Common
    "common.location": "Île-de-France, France",
    "common.available": "Disponible · Freelance & CDI",
    "lang.switch": "ES",
  },
  es: {
    // Navbar
    "nav.about": "Sobre mí",
    "nav.resume": "CV",
    "nav.projects": "Proyectos",
    "nav.contact": "Contacto",
    "nav.blog": "Blog",
    "nav.services": "Servicios",
    // Header
    "header.badge": "Desarrollador Full-stack · Founder & CEO · IA & Automatización",
    "header.greeting": "Soy",
    "header.name": "Andrew Alfaro",
    "header.description": "Desarrollador Full-stack apasionado por crear aplicaciones web de alto rendimiento y automatizar procesos empresariales con IA. Founder & CEO de Jumper Enterprise, especializado en React, Next.js, TypeScript y Deno. Más de 4 años de experiencia en Francia.",
    "header.cta.resume": "Ver mi CV",
    "header.cta.projects": "Mis Proyectos",
    "header.stat.years": "Años de experiencia",
    "header.stat.projects": "Proyectos entregados",
    "header.stat.companies": "Empresas",
    // Hero
    "hero.title1": "Creo",
    "hero.title2": "experiencias web excepcionales",
    "hero.subtitle": "Desarrollador Full-stack · Fundador Jumper Enterprise · Automatización IA · React · Next.js · TypeScript",
    "hero.cta": "Ver mis proyectos",
    // About
    "about.title": "Sobre mí",
    "about.intro": "Desarrollador Full-stack con más de 4 años de experiencia, fundador de Jumper Enterprise — una startup especializada en automatización de ventas y marketing con IA. Diseño aplicaciones web de alto rendimiento y automatizo procesos empresariales para maximizar la productividad.",
    "about.p1": "Mi expertise cubre el desarrollo front-end con React, Next.js y TypeScript, el desarrollo back-end con Node.js, Deno y PostgreSQL, así como la integración de agentes IA y automatizaciones vía n8n y Make.",
    "about.p2": "Como Founder & CEO de Jumper Enterprise, dirijo el desarrollo de soluciones de agentes IA para la gestión de ventas, marketing y soporte al cliente, permitiendo a las empresas operar 24/7 de forma automatizada.",
    "about.p3": "También contribuyo a proyectos open source como Yumi Lab, y me mantengo al día con las últimas tecnologías para aportar siempre más valor a mis clientes.",
    "about.education": "Educación & Certificaciones",
    "about.social": "Encuéntrame en",
    // Resume
    "resume.title": "CV Interactivo",
    "resume.subtitle": "Full-stack Developer · Founder & CEO · AI Solutions",
    "resume.summary": "Desarrollador Full-stack apasionado con más de 4 años de experiencia, especializado en JavaScript, React, TypeScript y Node.js. Fundador de Jumper Enterprise, experto en automatización de procesos empresariales con IA. Reconocido por mi autonomía, capacidad de innovación y dominio de arquitecturas modernas.",
    "resume.experience": "Experiencia Profesional",
    "resume.education": "Formación",
    "resume.skills": "Competencias Técnicas",
    "resume.languages": "Idiomas",
    "resume.softskills": "Soft Skills",
    "resume.contact": "Contacto",
    "resume.present": "Presente",
    // Services
    "services.title": "Mis Servicios",
    "services.subtitle": "Soluciones web a medida, automatización con IA y consultoría tecnológica para impulsar tu negocio.",
    "services.cta": "Ver todos mis servicios",
    "services.web.title": "Desarrollo Web Full-stack",
    "services.web.desc": "Aplicaciones React/Next.js de alto rendimiento, APIs REST, bases de datos y despliegue en la nube.",
    "services.ai.title": "Agentes IA & Automatización",
    "services.ai.desc": "Agentes inteligentes para ventas, marketing, soporte al cliente y gestión de operaciones vía n8n y Make.",
    "services.shopify.title": "E-Commerce & Shopify",
    "services.shopify.desc": "Tiendas Shopify personalizadas, integración de pagos Stripe/SEPA y optimización de conversiones.",
    // Services page
    "servicespage.hero.tag": "Disponible · Freelance & CDI",
    "servicespage.hero.title": "Transforma tus ideas en realidad",
    "servicespage.hero.subtitle": "Experto Full-stack & Founder de Jumper Enterprise. Diseño aplicaciones web de alto rendimiento y automatizo procesos empresariales con IA para impulsar tu crecimiento.",
    "servicespage.hero.cta.main": "Descubrir Jumper Enterprise",
    "servicespage.hero.cta.contact": "Hablemos de tu proyecto",
    "servicespage.offer.title": "Lo que ofrezco",
    "servicespage.offer.subtitle": "Soluciones a medida para startups, pymes y grandes empresas.",
    "servicespage.s1.title": "Desarrollo Web Full-stack",
    "servicespage.s1.desc": "Aplicaciones React/Next.js de alto rendimiento, SEO optimizado, APIs REST robustas e integraciones de terceros.",
    "servicespage.s1.f1": "React, Next.js, TypeScript",
    "servicespage.s1.f2": "APIs REST y bases de datos",
    "servicespage.s1.f3": "SSR / SSG / ISR",
    "servicespage.s1.f4": "Tests y despliegue CI/CD",
    "servicespage.s2.title": "Agentes IA & Automatización",
    "servicespage.s2.desc": "Agentes inteligentes para automatizar ventas, marketing, soporte al cliente y operaciones vía n8n, Make y Python.",
    "servicespage.s2.f1": "Agentes IA a medida",
    "servicespage.s2.f2": "Workflows n8n & Make",
    "servicespage.s2.f3": "Integración OpenAI / LLM",
    "servicespage.s2.f4": "Automatización 24/7",
    "servicespage.s3.title": "E-Commerce & Shopify",
    "servicespage.s3.desc": "Tiendas Shopify personalizadas, optimización de conversiones, integración Stripe/SEPA y dashboards de ventas.",
    "servicespage.s3.f1": "Temas Shopify a medida",
    "servicespage.s3.f2": "Stripe, SEPA, PayPal",
    "servicespage.s3.f3": "Dashboard KPI & analytics",
    "servicespage.s3.f4": "Mobile-first & SEO",
    "servicespage.s4.title": "Consultoría Tecnológica",
    "servicespage.s4.desc": "Auditoría de tu stack, recomendaciones de arquitectura, acompañamiento al equipo y formación en buenas prácticas.",
    "servicespage.s4.f1": "Auditoría & code review",
    "servicespage.s4.f2": "Arquitectura escalable",
    "servicespage.s4.f3": "Formación & mentoring",
    "servicespage.s4.f4": "Clean Code & CI/CD",
    "servicespage.process.title": "Mi proceso de trabajo",
    "servicespage.process.s1": "Descubrimiento",
    "servicespage.process.s1.desc": "Análisis de tus necesidades y definición del alcance",
    "servicespage.process.s2": "Diseño",
    "servicespage.process.s2.desc": "Arquitectura, maquetas y plan técnico detallado",
    "servicespage.process.s3": "Desarrollo",
    "servicespage.process.s3.desc": "Sprints ágiles con entregas regulares",
    "servicespage.process.s4": "Entrega",
    "servicespage.process.s4.desc": "Pruebas, despliegue y soporte post-lanzamiento",
    "servicespage.reviews.title": "Lo que dicen los clientes",
    "servicespage.reviews.loading": "Cargando opiniones...",
    "servicespage.reviews.empty": "¡Sé el primero en dejar una opinión!",
    "servicespage.review.form.title": "Dejar una opinión",
    "servicespage.review.form.name": "Tu nombre",
    "servicespage.review.form.name.ph": "Nombre o apodo...",
    "servicespage.review.form.comment": "Tu opinión",
    "servicespage.review.form.comment.ph": "Comparte tu experiencia...",
    "servicespage.review.form.submit": "Enviar opinión",
    "servicespage.review.form.rating": "Calificación",
    // Contact
    "contact.title": "Contáctame",
    "contact.subtitle": "Disponible para misiones freelance, oportunidades de empleo o colaboraciones. Respondo en menos de 24h.",
    "contact.name": "Nombre completo",
    "contact.name.ph": "Tu nombre...",
    "contact.email": "Email",
    "contact.email.ph": "tu@email.com",
    "contact.phone": "Teléfono",
    "contact.phone.ph": "+34 6XX XX XX XX",
    "contact.subject": "Asunto",
    "contact.subject.ph": "Proyecto web, freelance, empleo...",
    "contact.message": "Mensaje",
    "contact.message.ph": "Describe tu proyecto u oportunidad...",
    "contact.send": "Enviar mensaje",
    "contact.sending": "Enviando...",
    "contact.success": "¡Mensaje enviado! Te respondo en menos de 24h.",
    "contact.error": "Error al enviar. Por favor, inténtalo de nuevo.",
    "contact.info.title": "Mantengámonos en contacto",
    "contact.info.available": "Disponible ahora",
    "contact.info.location": "Île-de-France, Francia",
    "contact.info.response": "Respuesta en 24h",
    "contact.info.freelance": "Freelance & CDI",
    // Projects
    "projects.title": "Mis Proyectos",
    "projects.subtitle": "Aplicaciones web full-stack, automatización con IA, e-commerce y herramientas de desarrollo.",
    "projects.filter.all": "Todos",
    "projects.filter.web": "Web App",
    "projects.filter.ai": "IA & Auto",
    "projects.filter.ecommerce": "E-Commerce",
    "projects.filter.tools": "Herramientas",
    "projects.cta.details": "Ver detalles",
    "projects.cta.demo": "Demo",
    "projects.cta.code": "Código",
    "projects.featured": "Proyecto destacado",
    // Common
    "common.location": "Île-de-France, Francia",
    "common.available": "Disponible · Freelance & CDI",
    "lang.switch": "FR",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "fr",
  setLang: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>("fr");

  const t = (key: string): string => {
    return translations[lang][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = () => useContext(LanguageContext);
